// treeSpeciesData.js

const treeSpeciesData = {
  "Mallotus phillipensis": {
    "Bark Type": "Smooth",
    "Bark Colour": "Rusty/Pale Brown",
    "Leaf Arrangement": "Alternate",
    "Leaf shape": "oblong -obovate",
    "Leaf apex": "Acute or obtuse",
    "leaf margin": "Entire or Sinuate",
    "leaf base": "Obtuse",
    "Leaf surface": "Glabrous",
    "Flower arrangement": "Clustered",
    "Flower colour": "Yellow brown",
    "Fruit type": "Capsule",
    "Fruit shape": "Globose",
    "Fruit colour": "Red",
    "Leaf Type": "Leaf(Simple)" 
  },
  "Cleistanthus collinus": {
    "Bark Type": "Flacking off rounded thick scale",
    "Bark Colour": "Dark brown",
    "Leaf Arrangement": "Alternate",
    "Leaf shape": "Orbicular/Obovate",
    "Leaf apex": "Obtuse",
    "leaf margin": "Entire",
    "leaf base": "Rounded",
    "Leaf surface": "Glabrous",
    "Flower arrangement": "Clustered",
    "Flower colour": "Green",
    "Fruit type": "Capsule",
    "Fruit shape": "Globose",
    "Fruit colour": "Green/Brown",
    "Leaf Type": "Leaf (Simple)"
  },
  "test1": {
    "Bark Type": "Flacking off rounded thick scale",
    "Bark Colour": "Dark brown",
    "Leaf Arrangement": "Alternate",
    "Leaf shape": "Orbicular/Obovate",
    "Leaf apex": "Obtuse",
    "leaf margin": "Entire",
    "leaf base": "Rounded",
    "Leaf surface": "Glabrous",
    "Flower arrangement": "Clustered",
    "Flower colour": "Green",
    "Fruit type": "Capsule",
    "Fruit shape": "Globose",
    "Fruit colour": "Green/Brown",
    "Leaf Type": "Leaf (Simple)"
  },
  "test2": {
    "Bark Type": "Flacking off rounded thick scale",
    "Bark Colour": "Dark brown",
    "Leaf Arrangement": "Alternate",
    "Leaf shape": "Orbicular/Obovate",
    "Leaf apex": "Obtuse",
    "leaf margin": "Entire",
    "leaf base": "Rounded",
    "Leaf surface": "Glabrous",
    "Flower arrangement": "Clustered",
    "Flower colour": "Green",
    "Fruit type": "Capsule",
    "Fruit shape": "Globose",
    "Fruit colour": "Green/Brown",
    "Leaf Type": "Leaf (Simple)"
  },
"Emblica officinalis": {
  "Bark Type": "Irregular flakes",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong/Elliptic",
  "Leaf apex": "Mucranate/Obtuse",
  "leaf margin": "Entire/Denticulate/Ciliate",
  "leaf base": "Rounded ",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Green",
  "Fruit type": "Berry",
  "Fruit shape": "Subglobose",
  "Fruit colour": "Yellowish green",
  "Leaf Type": "Leaf (Simple)"
},
"Butea monosperma": {
  "Bark Type": "Fibrous/Crooked",
  "Bark Colour": "Grey to greyish brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Rhomboid",
  "Leaf apex4": "Emarginate",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Orange red",
  "Fruit type": "Pod",
  "Fruit shape": "Oblong",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Acacia leucophloea": {
  "Bark Type": "Smooth",
  "Bark Colour": "Yellow-Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Elliptic/Linear",
  "Leaf apex4": "Subacute",
  "leaf margin5": "Ciliate",
  "leaf base6": "Oblique/Truncate",
  "Leaf surface7": "Glabrous ",
  "Flower arrangement": "Clusterd",
  "Flower colour": "Yellow-white",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Elongated",
  "Fruit colour": "Rusty",
  "Leaf Type": "Leaf (Compound)"
},
"Delonix regia": {
  "Bark Type": "Smooth/Exfoliating",
  "Bark Colour": "Grey",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Truncate/Obliquely acute at base",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary/Pairs",
  "Flower colour": "Yellow/Orange",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Elongated",
  "Fruit colour": "Rusty",
  "Leaf Type": "Leaf (Compound)"
},
"Cassia fistula": {
  "Bark Type": "Smooth",
  "Bark Colour": "Dark Brown",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Oblong-Broadly ovate",
  "Leaf apex4": "Accuminate/Acute",
  "leaf margin5": "Entire",
  "leaf base6": "Subacute/Cuneate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clusters",
  "Flower colour": "Yellow",
  "Fruit type": "Pod",
  "Fruit shape": "Oblong/Cylindrical",
  "Fruit colour": "Dark brown",
  "Leaf Type": "Leaf (Compound)"
},
"Cassia siamea": {
  "Bark Type": "Fissured/Smooth",
  "Bark Colour": "Greyish brown",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Rounded",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellow",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Elongated",
  "Fruit colour": "Dark brown",
  "Leaf Type": "Leaf (Compound)"
},
"Saraca asoca": {
  "Bark Type": "Lenticle",
  "Bark Colour": "Balze purplish",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Elliptic/Oblong",
  "Leaf apex4": "Accuminate/Acute",
  "leaf margin5": "Entire",
  "leaf base6": "Rounded/Subcordate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Orange red",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Oblong",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Parkia biglandulosa": {
  "Bark Type": "Smooth/Fissured",
  "Bark Colour": "Greyish black",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Linear",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique/Truncate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Elongated",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Albizia lebbeck": {
  "Bark Type": "Deeply Fissured",
  "Bark Colour": "Yellowish brown",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Base of one half Cuneate, Other half round",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Greenish white",
  "Fruit type": "Pod",
  "Fruit shape": "Flat",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Albizia procera": {
  "Bark Type": "Smooth",
  "Bark Colour": "White",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Obliquely Oblong",
  "Leaf apex4": "Obtuse/Subacute",
  "leaf margin5": "Entire",
  "leaf base6": "Unequal",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Yellowish white",
  "Fruit type": "Pod",
  "Fruit shape": "Flat",
  "Fruit colour": "Reddish Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Dalbergia sissoo": {
  "Bark Type": "Furrowed",
  "Bark Colour": "Dark Grey",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Orbiculate/Broadly ovate/Oval",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Rounded",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish white",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Oblong",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Pongamia pinnata": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Ovate/Oblong",
  "Leaf apex4": "Obtuse/Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Cuneate/Rounded",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White/Purple/Pink",
  "Fruit type": "Pod",
  "Fruit shape": "Flat/Ellipticle",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Tamarindus indica": {
  "Bark Type": "Furrowed",
  "Bark Colour": "Dark brown",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Unequal",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Yellow reddish pink",
  "Fruit type": "Pod",
  "Fruit shape": "Oblong",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Pterocarpus marsupium": {
  "Bark Type": "Deeply vertically cracked/Exfoliations/Fibrous",
  "Bark Colour": "Greyish black",
  "Leaf Arrangement2": "Aletrnate",
  "Leaf shape3": "Elliptic/Oblong",
  "Leaf apex4": "Obtuse/Emarginate",
  "leaf margin5": "Entire",
  "leaf base6": "Obtuse/Acute",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellow",
  "Fruit type": "Pod",
  "Fruit shape": "Orbicular/Reniform/Winged",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Ficus benghalensis ": {
  "Bark Type": "Smooth",
  "Bark Colour": "Greyish brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate-Elliptic",
  "Leaf apex": "Obtuse-Subacute",
  "leaf margin": "Entire",
  "leaf base": "Rounded/Subcordate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Syconus/Pairs",
  "Flower colour": "Red",
  "Fruit type": "Syconus/Achene",
  "Fruit shape": "Globose",
  "Fruit colour": "Scarlet red",
  "Leaf Type": "Leaf(Simple)"
},
"Ficus carica": {
  "Bark Type": "Fissured-Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong-Lobed",
  "Leaf apex": "Acute ",
  "leaf margin": "Undulate/Dentate",
  "leaf base": "Cordate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Syconus/Pairs",
  "Flower colour": "Green",
  "Fruit type": "Syconus",
  "Fruit shape": "Subglobose",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Ficus benjamina": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ellipticle",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Rounded",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Syconus/Pairs",
  "Flower colour": "Red/Yellow",
  "Fruit type": "Syconus/Achene",
  "Fruit shape": "Ovoid/Reniform",
  "Fruit colour": "Red/Yellow",
  "Leaf Type": "Leaf(Simple)"
},
"Ficus recemosa": {
  "Bark Type": "Smooth",
  "Bark Colour": "Reddish brown/Yellowish brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Lanceolate/Ovate/Obovate/Elliptic/Oblong",
  "Leaf apex": "Obtuse/Acute",
  "leaf margin": "Entire",
  "leaf base": "Acute/Obtuse/Cuneate",
  "Leaf surface": "Pubescent",
  "Flower arrangement": "Syconus/Clusters ",
  "Flower colour": "Red\Brown",
  "Fruit type": "Syconus/Achene",
  "Fruit shape": "Subglobose/Pyriform",
  "Fruit colour": "Orange/Pink/Dark crimson",
  "Leaf Type": "Leaf(Simple)"
},
"Ficus religiosa": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Cordate/Ovate-Lanceolate",
  "Leaf apex": "Caudate-Accuminated",
  "leaf margin": "Entire-Wavy",
  "leaf base": "Truncate/Undulate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Syconus/Pairs",
  "Flower colour": "Green",
  "Fruit type": "Achene",
  "Fruit shape": "Globose",
  "Fruit colour": "Pink/Black",
  "Leaf Type": "Leaf(Simple)"
},
"Ficus hispida": {
  "Bark Type": "Lenticellate",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Opposite",
  "Leaf shape": "Elliptic-Oblong",
  "Leaf apex": "Caudate-Accuminated",
  "leaf margin": "Dentate (Rarely Entire)",
  "leaf base": "Rounded/Subcordate",
  "Leaf surface": "Scabrid",
  "Flower arrangement": "Syconium/Pairs",
  "Flower colour": "Green",
  "Fruit type": "Syconus",
  "Fruit shape": "Globose",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Ficus virens": {
  "Bark Type": "Smooth",
  "Bark Colour": "Pale/Greenish Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Subundulate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Syconium/Pairs/Clustered",
  "Flower colour": "White-Purp-lish",
  "Fruit type": "Syconus",
  "Fruit shape": "Globose",
  "Fruit colour": "White",
  "Leaf Type": "Leaf(Simple)"
},
"Morus alba": {
  "Bark Type": "Fissured ",
  "Bark Colour": "Dark Grey-Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate",
  "Leaf apex": "Obtuse/Acute/Acuminate",
  "leaf margin": "Serrate",
  "leaf base": "Cordate ",
  "Leaf surface": "Pubescent",
  "Flower arrangement": "Catkin",
  "Flower colour": "Greenish white",
  "Fruit type": "Sorosis",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Pinkish Purple/Black",
  "Leaf Type": "Leaf (Simple)"
},
"Artocarpus hetereophyllus": {
  "Bark Type": "Exfoliating in large thick flakes",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate-Lanceolate/Obovate-Oblong/Elliptic-Obovate",
  "Leaf apex": "Obtuse-Short Acuminate",
  "leaf margin": "Entire   ",
  "leaf base": "Cuneate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Catkin",
  "Flower colour": "Green ",
  "Fruit type": "Pod/Broadly Winged",
  "Fruit shape": "Globose-Obovoid",
  "Fruit colour": "Yellowish-Green ",
  "Leaf Type": "Leaf (Simple)"
},
"Casuarina equisetifolia": {
  "Bark Type": "Scaly/Furrowed",
  "Bark Colour": "Greyish ",
  "Leaf Arrangement": "Whorl",
  "Leaf shape": "Scaly filliform",
  "Flower arrangement": "Spikes/Cones",
  "Flower colour": "Brown",
  "Fruit type": "Samara",
  "Fruit shape": "Globose",
  "Fruit colour": "Dark brownish",
  "Leaf Type": "Leaf (Simple)"
},
"Anogeissus latifolia": {
  "Bark Type": "Smooth",
  "Bark Colour": "Yellowish Grey",
  "Leaf Arrangement": "Opposite/Alternate",
  "Leaf shape": "Elliptic ",
  "Leaf apex": "Obtuse/Emerginate or Mucronate",
  "leaf margin": "Entire",
  "leaf base": "Rounded-Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered/Aggregate globose",
  "Flower colour": "Pale Green-Yellow",
  "Fruit type": "Drupe",
  "Fruit shape": "Globose",
  "Fruit colour": "Red- Green",
  "Leaf Type": "Leaf(Simple)"
},
"Anogeissus pendula": {
  "Bark Type": "Smooth",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Lanceolate",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered/Aggregate globose",
  "Flower colour": "Pinkish-Yellow",
  "Fruit type": "Drupe",
  "Fruit shape": "Globose",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf(Simple)"
},
"Terminalia chebula": {
  "Bark Type": "Irregular flakes/Fissured",
  "Bark Colour": "Greyish Brown",
  "Leaf Arrangement": "Alternate/Subopposite",
  "Leaf shape": "Elliptic-Ovate",
  "Leaf apex": "Acute-Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Rounded",
  "Leaf surface": "Pubescent",
  "Flower arrangement": "Spikes",
  "Flower colour": "Greenish-White",
  "Fruit type": "Drupe",
  "Fruit shape": "Obovoid",
  "Fruit colour": "Greenis-Yellow",
  "Leaf Type": "Leaf (Simple)"
},
"Terminalia alata": {
  "Bark Type": "Cracked/Fissured",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Elliptic/Elliptic-Ovate",
  "Leaf apex": "Acute",
  "leaf margin": "Entire/Rarely Cranulate",
  "leaf base": "Cordate/Obtuse",
  "Leaf surface": "Pubescent",
  "Flower arrangement": "Spikes",
  "Flower colour": "Greenish yellow",
  "Fruit type": "Papery Wings",
  "Fruit shape": "Broadly Ellipsoid",
  "Fruit colour": "Black/Green",
  "Leaf Type": "Leaf (Simple)"
},
"Terminalia bellirica": {
  "Bark Type": "Fissured",
  "Bark Colour": "Whitish Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Broadly Elliptic-Obovate",
  "Leaf apex": "Acute /Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cuneate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Spikes",
  "Flower colour": "Creamy White/Greenish Yellow",
  "Fruit type": "Drupe",
  "Fruit shape": "Globose/Ovoid",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Terminalia arjuna": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong-Obovate",
  "Leaf apex": "Obtuse/Acute",
  "leaf margin": "Crenate-Serrate",
  "leaf base": "Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Spikes",
  "Flower colour": "Creamy White/Greenish Yellow",
  "Fruit type": "Papery Winged",
  "Fruit shape": "Ellipsoid",
  "Fruit colour": "Black/Green",
  "Leaf Type": "Leaf(Simple)"
},
"Terminalia catappa": {
  "Bark Type": "Smooth",
  "Bark Colour": "Brown ",
  "Leaf Arrangement": "Opposite/Rosett",
  "Leaf shape": "Cuneate to obovate-Spatualte",
  "Leaf apex": "Fimbriate",
  "leaf margin": "Entire",
  "leaf base": "Attenuate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Spikes",
  "Flower colour": "Creamy White",
  "Fruit type": "Drupe",
  "Fruit shape": "Ellipsoid",
  "Fruit colour": "Pale Green",
  "Leaf Type": "Leaf(Simple)"
},
"Lagerstroemia parviflora": {
  "Bark Type": "Furrowed",
  "Bark Colour": "Brown/Greyish black",
  "Leaf Arrangement": "Opposite",
  "Leaf shape": "Oblong-Elliptic",
  "Leaf apex": "Acute/Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Rounded",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Capsule",
  "Fruit shape": "Ovate-Suborbicular",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Lagerstroemia spesiosa": {
  "Bark Type": "Smooth/Flaky",
  "Bark Colour": "Brown/Light Grey",
  "Leaf Arrangement": "Opposite",
  "Leaf shape": "Elliptic-Oblong/Lanceolate",
  "Leaf apex": "Acute",
  "leaf margin": "Entire",
  "leaf base": "Rounded",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Purple/Pink",
  "Fruit type": "Capsule",
  "Fruit shape": "Globose",
  "Fruit colour": "Woody Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Syzygium cumini": {
  "Bark Type": "Flakes",
  "Bark Colour": "Brown/Greyish ",
  "Leaf Arrangement": "Opposite",
  "Leaf shape": "Ellip[tic-Ovate/Lanceolate",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cuneate-Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Creamy White",
  "Fruit type": "Berry",
  "Fruit shape": "Oblong",
  "Fruit colour": "Black",
  "Leaf Type": "Leaf (Simple)"
},
"Eucalyptus grandis": {
  "Bark Type": "Smooth/Flakes",
  "Bark Colour": "White",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Lanceolate",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Oblique/Obtuse/Attenuate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": " White",
  "Fruit type": "Capsule",
  "Fruit shape": "Pyriform",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Anacardium occidentale": {
  "Bark Type": "Irregulary Shaped ",
  "Bark Colour": "Brown/Dark Brown",
  "Leaf Arrangement": "Spirally/Alternate",
  "Leaf shape": "Elliptic-Obovate",
  "Leaf apex": "Acute/Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cuneate/Rounded",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Pink/White",
  "Fruit type": "Nut",
  "Fruit shape": "Kidney Shaped/Pear shaped",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Buchanania lanzan": {
  "Bark Type": "Tessellate crack",
  "Bark Colour": "Dark Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Broadly Oblong",
  "Leaf apex": "Obtuse/Emarginate",
  "leaf margin": "Entire",
  "leaf base": "Rounded",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Greenish-White",
  "Fruit type": "Drupe",
  "Fruit shape": "Oblong",
  "Fruit colour": "Black/Green",
  "Leaf Type": "Leaf (Simple)"
},
"Lannea coromandelica": {
  "Bark Type": "Fibrous",
  "Bark Colour": "Grey/White",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Oblong-Ovate",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique/Rounded",
  "Leaf surface7": "Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish Green",
  "Fruit type": "Drupe",
  "Fruit shape": "Subglobose/Ovoid",
  "Fruit colour": "Reddish Purple ",
  "Leaf Type": "Leaf (Compound)"
},
"Mangifera indica": {
  "Bark Type": "Scaly/Furrowed",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong/Elliptic/Lanceolate",
  "Leaf apex": "Rounded/Acuminate",
  "leaf margin": "Slightly Undulate",
  "leaf base": "Acute/Attenuate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Greenish White/Pink",
  "Fruit type": "Drupe",
  "Fruit shape": "Round/Oval/Caudate",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf (Simple)"
},
"Semecarpus anacardium": {
  "Bark Type": "Furrowed",
  "Bark Colour": "Reddish Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong",
  "Leaf apex": "Rounded",
  "leaf margin": "Entire",
  "leaf base": "Rounded/Cuneate",
  "Leaf surface": "Pubscent",
  "Flower arrangement": "Clustered",
  "Flower colour": "Greenish White",
  "Fruit type": "Drupe",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Black/Green",
  "Leaf Type": "Leaf (Simple)"
},
"Azadirachta indica": {
  "Bark Type": "Cracked/Fissured",
  "Bark Colour": "Greyish Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Lanceolate/Ovate",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Serrate",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clusterd",
  "Flower colour": "White",
  "Fruit type": "Drupe",
  "Fruit shape": "Oblong-Ovoid",
  "Fruit colour": "Greenish Yellow",
  "Leaf Type": "Leaf (Compound)"
},
"Melia azedarach": {
  "Bark Type": "Flakes",
  "Bark Colour": "Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Ovate/Lanceolate",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Serrate/Lobed",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clusterd",
  "Flower colour": "Purple/White",
  "Fruit type": "Drupe",
  "Fruit shape": "Ellipsoid/Globose",
  "Fruit colour": "Yellow",
  "Leaf Type": "Leaf (Compound)"
},
"Soymida febrifuga": {
  "Bark Type": "Cracked/Fissured",
  "Bark Colour": "Brown/Black",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Elliptic/Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Unequal",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clusterd",
  "Flower colour": "White",
  "Fruit type": "Capsule",
  "Fruit shape": "Obovoid",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf (Compound)"
},
"Aegle marmelos": {
  "Bark Type": "Flakes/Finely Fissured",
  "Bark Colour": "Pale Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Ovate/lanceolate",
  "Leaf apex4": "Acute",
  "leaf margin5": "Crenate-Serrate",
  "leaf base6": "Rounded/Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Greenish White",
  "Fruit type": "Berries",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Yellowish green",
  "Leaf Type": "Leaf (Compound)"
},
"Murraya koenigii": {
  "Bark Type": "Flakes",
  "Bark Colour": "Brown/Dark Brown",
  "Leaf Arrangement2": "Alternate-Spiral",
  "Leaf shape3": "Oblong-Lanceolate",
  "Leaf apex4": "Emarginate",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Berries",
  "Fruit shape": "Subglobose",
  "Fruit colour": "Purplish-Black",
  "Leaf Type": "Leaf (Compound)"
},
"Limonia accidissima": {
  "Bark Type": "Spiny/Fissured-Flakes ",
  "Bark Colour": "Dark Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Obovate",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Cuneate/Acute",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Berries",
  "Fruit shape": "Globose",
  "Fruit colour": "woody white",
  "Leaf Type": "Leaf (Compound)"
},
"Chloroxylon swietenia": {
  "Bark Type": "Fissured/Corky Bark",
  "Bark Colour": "Dark Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Capsule",
  "Fruit shape": "Loculicidal",
  "Fruit colour": "Brown/Green",
  "Leaf Type": "Leaf (Compound)"
},
"Simarouba glauca": {
  "Bark Type": "Smooth",
  "Bark Colour": "Reddish Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Oblong",
  "Leaf apex4": "Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish White",
  "Fruit type": "Drupe",
  "Fruit shape": "Oval",
  "Fruit colour": "Black/Green",
  "Leaf Type": "Leaf (Compound)"
},
"Bixa orellana": {
  "Bark Type": "Smooth",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate/Cordate",
  "Leaf apex": "Acuminate/Acute",
  "leaf margin": "Entire",
  "leaf base": "Cordate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Pink",
  "Fruit type": "Capsule/Pod",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Reddish Brown",
  "Leaf Type": "Leaf(Simple)"
},
"Shorea robusta": {
  "Bark Type": "Fissured",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Laceolate-Ovate/Oblanceolate-Elliptic",
  "Leaf apex": "Acute/Rounded",
  "leaf margin": "Entire",
  "leaf base": "Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White/Creamy White",
  "Fruit type": "Capsule/Winged",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Reddish Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Bombax ceiba": {
  "Bark Type": "Fissured/Conical prickles",
  "Bark Colour": "Grey",
  "Leaf Arrangement2": "Whorl/Alternate",
  "Leaf shape3": "Elliptic/Ovate/Elliptic-Obovate",
  "Leaf apex4": "Caudate-Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Attenuate-Cuneate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Red",
  "Fruit type": "Capsule",
  "Fruit shape": "Cylindrical",
  "Fruit colour": "Woody Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Ceiba pentandra": {
  "Bark Type": "Smooth",
  "Bark Colour": "White/Grey",
  "Leaf Arrangement2": "Whorl/Alternate",
  "Leaf shape3": "Elliptic/Obovate-Oblong/Ovate-Oblong",
  "Leaf apex4": "Acute-Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Acute/Cuneate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary/Clustered",
  "Flower colour": "Creamy White",
  "Fruit type": "Capsule",
  "Fruit shape": "Ellipsoid-Fusiform",
  "Fruit colour": "Woody Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Sterculia urens": {
  "Bark Type": "Smooth/Fibrous",
  "Bark Colour": "White/Pink",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Palmate",
  "Leaf apex": "Acuminate/Cordate-Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cordate/Sagittate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Greenish yellow",
  "Fruit type": "Aggregate Follicle",
  "Fruit shape": "Ovoid-Oblong",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Thespesia populnea": {
  "Bark Type": "Cracked/Fissured",
  "Bark Colour": "Dark Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Cordate/Orbicular/Ovate",
  "Leaf apex": "Acute/Acuminate",
  "leaf margin": "Entire/Dentate",
  "leaf base": "Cordate/Truncate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Yellow/Pink",
  "Fruit type": "Capsule",
  "Fruit shape": "Globose",
  "Fruit colour": "Green/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Moringa oleifera": {
  "Bark Type": "Corky",
  "Bark Colour": "Brown/Grey",
  "Leaf Arrangement2": "Alternate/Spiral",
  "Leaf shape3": "Elliptic-Ovate/Obovate",
  "Leaf apex4": "Rounded",
  "leaf margin5": "Entire",
  "leaf base6": "Rounde",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary/Clustered",
  "Flower colour": "White",
  "Fruit type": "Capsule",
  "Fruit shape": "Elongated",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf (Compound)"
},
"Diospyrus melanoxylon": {
  "Bark Type": "Corky/Fissured",
  "Bark Colour": "Black/Dark Brown",
  "Leaf Arrangement": "Opposite-Alternate",
  "Leaf shape": "Elliptic/Oblong",
  "Leaf apex": "Obtuse",
  "leaf margin": "Entire",
  "leaf base": "Acute/Obtuse",
  "Leaf surface": "Pubescent/Glabrous",
  "Flower arrangement": "Solitary/Clustered",
  "Flower colour": "Brown/White",
  "Fruit type": "Berry",
  "Fruit shape": "Globose",
  "Fruit colour": "Yellow",
  "Leaf Type": "Leaf (Simple)"
},
"Couroupita guinenesis": {
  "Bark Type": "Fissured",
  "Bark Colour": "Brown/Black",
  "Leaf Arrangement": "Alternate/Whorl",
  "Leaf shape": "Oblong-Obovate",
  "Leaf apex": "Acute-Acuminate",
  "leaf margin": "Entire/Serrate",
  "leaf base": "Acute",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Solitary/Pairs/Clustered",
  "Flower colour": "Red",
  "Fruit type": "Capsule",
  "Fruit shape": "Globose",
  "Fruit colour": "Reddish-Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Careya arborea": {
  "Bark Type": "Smooth/Fibrous",
  "Bark Colour": "White/Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate-Obovate",
  "Leaf apex": "Rounded/Acuminate",
  "leaf margin": "Crenate/Serrate",
  "leaf base": "Cuneate/Attenuate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Red/White",
  "Fruit type": "Berry",
  "Fruit shape": "Globose",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf (Simple)"
},
"Madhuca longifolia": {
  "Bark Type": "Cracked/Scales",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Elliptic",
  "Leaf apex": "Acute/Acuminate/Apiculate",
  "leaf margin": "Entire",
  "leaf base": "Obtuse/Cuneate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish White",
  "Fruit type": "Berry",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf (Simple)"
},
"Mimusops elengi": {
  "Bark Type": "Fissured/Lenticillate",
  "Bark Colour": "Reddish Brown/Blaze Pink",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Elliptic-Oblong",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Obtuse",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Solitary/Clustered",
  "Flower colour": "Yellowish White",
  "Fruit type": "Berry",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Green/Blaze red",
  "Leaf Type": "Leaf (Simple)"
},
"manilkara zapota": {
  "Bark Type": "Furrowed",
  "Bark Colour": "Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Elliptic-Lanceolate",
  "Leaf apex": "Acute-Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Acute",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish White",
  "Fruit type": "Berry",
  "Fruit shape": "Globose",
  "Fruit colour": "Reddish Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Gardenia latifolia": {
  "Bark Type": "Smooth",
  "Bark Colour": "Whitish Yellow",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Broadly Elliptic-Orbicular",
  "Leaf apex": "Obtuse-Acute",
  "leaf margin": "Entire",
  "leaf base": "Rounded-Attenuate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Solitary",
  "Flower colour": "Yellowish White",
  "Fruit type": "Berry",
  "Fruit shape": "Globose",
  "Fruit colour": "Green/Black",
  "Leaf Type": "Leaf(Simple)"
},
"Haldina cordifolia": {
  "Bark Type": "Exfoliating in Small thick flakes",
  "Bark Colour": "Grey-Brown",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Orbicular/Ovate/Cordate",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cordate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered/Dense Head",
  "Flower colour": "Yellow",
  "Fruit type": "Capsule",
  "Fruit shape": "Obconical",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Mitragyna parvifolia": {
  "Bark Type": "Fibrous",
  "Bark Colour": "Grey/Black",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Elliptic/Ovate-Oblong",
  "Leaf apex": "Acute/Subcordate/Obtuse",
  "leaf margin": "Entire",
  "leaf base": "Obtuse/Attenuate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered/Dense Head",
  "Flower colour": "Creamy White",
  "Fruit type": "Capsule",
  "Fruit shape": "Obconical",
  "Fruit colour": "Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Wendlandia heynei": {
  "Bark Type": "Cracked/Exfoliating",
  "Bark Colour": "Reddish Brown",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Lanceolate/Oblong",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cuneate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "white",
  "Fruit type": "Capsule",
  "Fruit shape": "Globose",
  "Fruit colour": "Grey/Brown",
  "Leaf Type": "Leaf (Simple)"
},
"Neolamarckia cadamba": {
  "Bark Type": "Exfoliating In small rectangualr flakes",
  "Bark Colour": "Pale Brown",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Ovate/Elliptic-Oblong",
  "Leaf apex": "Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Truncate/Obtuse",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered/Dense Head",
  "Flower colour": "Yellowish",
  "Fruit type": "Capsule",
  "Fruit shape": "Globose",
  "Fruit colour": "Orange/Yellow",
  "Leaf Type": "Leaf (Simple)"
},
"Tamilnadia uliginosa": {
  "Bark Type": "Smooth",
  "Bark Colour": "Dark Brown/Black",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Obovate/Oblanceolate-Oblong",
  "Leaf apex": "Obtuse",
  "leaf margin": "Entire",
  "leaf base": "Cuneate/Attenuate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Solitary",
  "Flower colour": "White",
  "Fruit type": "Berry",
  "Fruit shape": "Ovoid/Ellipsoid",
  "Fruit colour": "Green/Yellow",
  "Leaf Type": "Leaf(Simple)"
},
"Wrightia tinctoria": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Oblong -Lanceolate/Elliptic-Ovate",
  "Leaf apex": "Acuminate/Caudate",
  "leaf margin": "Entire",
  "leaf base": "Acute",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Follicle",
  "Fruit shape": "Cylindrical",
  "Fruit colour": "Green",
  "Leaf Type": "Leaf(Simple)"
},
"Cordia dichotoma": {
  "Bark Type": "Smooth",
  "Bark Colour": "Grey/White",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Ovate/Elliptic-Oblong",
  "Leaf apex": "Acute/Acuminate",
  "leaf margin": "Subentire/Sinuate-dentate/Crenate",
  "leaf base": "Rounded/Cuneate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Drupe",
  "Fruit shape": "Conical",
  "Fruit colour": "Pinkish Yellow/Green",
  "Leaf Type": "Leaf(Simple)"
},
"Cordia macleodii": {
  "Bark Type": "Smooth",
  "Bark Colour": "Brown/White",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Cordate/Ovate",
  "Leaf apex": "Acuminate/Obtuse",
  "leaf margin": "Sinuate-Wavy",
  "leaf base": "Cordate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Drupe",
  "Fruit shape": "Orbicular-Ovate",
  "Fruit colour": "Yellow/Green",
  "Leaf Type": "Leaf(Simple)"
},
"Ehretia laevis": {
  "Bark Type": "Smooth",
  "Bark Colour": "Pale Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Elliptic",
  "Leaf apex": "Shortly Acuminate",
  "leaf margin": "Entire",
  "leaf base": "Cuneate",
  "Leaf surface": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Drupe",
  "Fruit shape": "Subglobose",
  "Fruit colour": "Red",
  "Leaf Type": "Leaf(Simple)"
},
"Oroxylum indicum": {
  "Bark Type": "Smooth/Corky Lenticels",
  "Bark Colour": "Brownish Grey",
  "Leaf Arrangement2": "Opposite",
  "Leaf shape3": "Ovate",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Cordate/Oblique-Truncate",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Solitary",
  "Flower colour": "Pinkish-Yellow",
  "Fruit type": "Capsule",
  "Fruit shape": "Flat",
  "Fruit colour": "Purple/Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Spathodea campanulata": {
  "Bark Type": "Lenticellate",
  "Bark Colour": "Brown",
  "Leaf Arrangement2": "Opposite",
  "Leaf shape3": "Elliptic-Ovate",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Obtuse",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Orange/Yellow",
  "Fruit type": "Capsule",
  "Fruit shape": "Lanceolate",
  "Fruit colour": "Brown/Green",
  "Leaf Type": "Leaf (Compound)"
},
"Milingtonia hortensis": {
  "Bark Type": "Cracked",
  "Bark Colour": "Brown",
  "Leaf Arrangement2": "Opposite",
  "Leaf shape3": "Elliptic/Ovate-Oblong",
  "Leaf apex4": "Acuminate",
  "leaf margin5": "Entire",
  "leaf base6": "Rounded/Oblique",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Capsule",
  "Fruit shape": "Linear",
  "Fruit colour": "Brown/Reddish Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Tectona grandis": {
  "Bark Type": "Elongated Peeling/Fissured/Fibrous",
  "Bark Colour": "Pale Brown",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Ovate-Obovate",
  "Leaf apex": "Acute/Obtuse",
  "leaf margin": "Entire/Wavy",
  "leaf base": "Attenuate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "White",
  "Fruit type": "Drupe",
  "Fruit shape": "Globose",
  "Fruit colour": "Brown/Green",
  "Leaf Type": "Leaf (Simple)"
},
"Gmelina arborea": {
  "Bark Type": "Smooth",
  "Bark Colour": "Yellowish Brown/Pale Brown",
  "Leaf Arrangement": "Opposite-Decussate",
  "Leaf shape": "Ovate-Cordate",
  "Leaf apex": "Acuminate-Caudate",
  "leaf margin": "Serrate",
  "leaf base": "Cordate/Truncate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Solitary/Paired/Clustered",
  "Flower colour": "Yellow/Orange",
  "Fruit type": "Drupe",
  "Fruit shape": "Obovoid",
  "Fruit colour": "Green/Yellow",
  "Leaf Type": "Leaf(Simple)"
},
"Schrebera swietenioides": {
  "Bark Type": "Scaled",
  "Bark Colour": "Greyish-White",
  "Leaf shape3": "Elliptic-Lanceolate/Ovate/Elliptic-Obovate",
  "Leaf apex4": "Acute",
  "leaf margin5": "Entire",
  "leaf base6": "Attenuate/Oblique",
  "Leaf surface7": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "Yellowish-Brown",
  "Fruit type": "Capsule",
  "Fruit shape": "Obovoid",
  "Fruit colour": "Yellowish Brown",
  "Leaf Type": "Leaf (Compound)"
},
"Alangium salvifolium": {
  "Bark Type": "Fissured",
  "Bark Colour": "Brown/Pale Brown",
  "Leaf Arrangement": "Alternate",
  "Leaf shape": "Oblong/Lanceolate",
  "Leaf apex": "Acute-Subobtuse",
  "leaf margin": "Entire",
  "leaf base": "Cuneate",
  "Leaf surface": "Glabrous/Pubescent",
  "Flower arrangement": "Clustered",
  "Flower colour": "Creamy White",
  "Fruit type": "Berry",
  "Fruit shape": "Globose",
  "Fruit colour": "Red",
  "Leaf Type": "Leaf (Simple)"
},
"Schleichera oleosa": {
  "Bark Type": "Smooth/Crooked",
  "Bark Colour": "Brown/Reddish Brown",
  "Leaf Arrangement2": "Alternate",
  "Leaf shape3": "Elliptic-Oblong/Ovate-Oblong",
  "Leaf apex4": "Acute/Obtuse",
  "leaf margin5": "Entire",
  "leaf base6": "Oblique/Rarely Obtuse",
  "Leaf surface7": "Glabrous",
  "Flower arrangement": "Clustered",
  "Flower colour": "Greenish Yellow",
  "Fruit type": "Drupe",
  "Fruit shape": "Ovoid",
  "Fruit colour": "Yellowish green",
  "Leaf Type": "Leaf (Compound)"
},
};
export default treeSpeciesData;
